[versions]

android-compileSdk = "36"
android-minSdk = "30"
android-targetSdk = "36"

agp = "9.0.0-rc02"
androidx-activity = "1.12.2"
androidx-lifecycle = "2.9.6"
coil = "3.3.0"
cmp = "1.11.0-alpha01"
composeHotReload = "1.0.0"
coroutines = "1.10.2"
kermit = "2.0.8"
koin-bom = "4.1.1"
koin-annotations = "2.3.1"
kotlin = "2.3.0"
kotlinx-serialization = "1.9.0"
ksp = "2.3.3"
ktor = "3.3.3"
paging = "3.3.0-alpha02-0.5.1"
room = "2.8.4"
sqlite = "2.6.2"
coreKtx = "1.17.0"
multiplatform-nav3-ui = "1.0.0-alpha06"
compose-multiplatform-lifecycle = "2.10.0-alpha07"
uiTooling = "1.10.0"
compose-adaptive = "1.3.0-alpha03"
kotlinx-datetime = "0.7.1"
mockk = "1.14.7"

[libraries]

# Kotlin
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

# Android
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "uiTooling" }

# Koin
koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koin-bom" }
koin-core = { group = "io.insert-koin", name = "koin-core" }
koin-compose = { group = "io.insert-koin", name = "koin-compose" }
koin-compose-viewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel" }
koin-compose-viewmodel-navigation = { group = "io.insert-koin", name = "koin-compose-viewmodel-navigation" }
koin-test = { group = "io.insert-koin", name = "koin-test" }
koin-test-junit4 = { group = "io.insert-koin", name = "koin-test-junit4" }

# Koin Annotations
koin-annotations-bom = { group = "io.insert-koin", name = "koin-annotations-bom", version.ref = "koin-annotations" }
koin-annotations = { group = "io.insert-koin", name = "koin-annotations", version.ref = "koin-annotations" }
koin-ksp-compiler = { group = "io.insert-koin", name = "koin-ksp-compiler", version.ref = "koin-annotations" }

# Coil
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-network-ktor3 = { group = "io.coil-kt.coil3", name = "coil-network-ktor3", version.ref = "coil" }

# Ktor
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio-jvm", version.ref = "ktor" }
ktor-client-encoding = { group = "io.ktor", name = "ktor-client-encoding", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-client-auth = { group = "io.ktor", name = "ktor-client-auth", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }

# Paging
paging-common = { group = "app.cash.paging", name = "paging-common", version.ref = "paging" }
paging-compose-common = { group = "app.cash.paging", name = "paging-compose-common", version.ref = "paging" }

# Room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-sqlite-bundled = { group = "androidx.sqlite", name = "sqlite-bundled", version.ref = "sqlite" }

# Logging
kermit = { group = "co.touchlab", name = "kermit", version.ref = "kermit" }

# Compose Runtime
compose-runtime = { group = "org.jetbrains.compose.runtime", name = "runtime", version.ref = "cmp" }
compose-foundation = { group = "org.jetbrains.compose.foundation", name = "foundation", version.ref = "cmp" }
compose-components-resources = { group = "org.jetbrains.compose.components", name = "components-resources", version.ref = "cmp" }
compose-ui-tooling-preview = { group = "org.jetbrains.compose.ui", name = "ui-tooling-preview", version.ref = "cmp" }
compose-ui = { group = "org.jetbrains.compose.ui", name="ui", version.ref = "cmp" }

compose-material3 = { group = "org.jetbrains.compose.material3", name = "material3", version = "cmp" }
compose-window-size = { group = "org.jetbrains.compose.material3", name = "material3-window-size-class" , version ="1.9.0"}

compose-adaptive = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive", version.ref = "compose-adaptive" }
compose-adaptive-layout = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive-layout", version.ref = "compose-adaptive" }
compose-adaptive-navigation = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive-navigation", version.ref = "compose-adaptive" }

jetbrains-navigation3-ui = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version.ref = "multiplatform-nav3-ui" }
jetbrains-lifecycle-viewmodelNavigation3 = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "compose-multiplatform-lifecycle" }

# Kotlinx
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }

# Mockk
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }
mockk-agent = { group = "io.mockk", name = "mockk-agent", version.ref = "mockk" }

# Dependencies of the included build-logic
gradle-plugin-android = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
gradle-plugin-compose = { group = "org.jetbrains.compose", name = "org.jetbrains.compose.gradle.plugin", version.ref = "cmp" }
gradle-plugin-kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-plugin-room = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "room" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

[bundles]

kotlin-common = [
    "kotlin-stdlib",
    "kotlinx-datetime"
]
kotlin-common-test = [
    "kotlin-test",
    "kotlinx-coroutines-test"
]
kotlin-android-test = [
    "mockk-android",
    "mockk-agent"
]

# Ktor
ktor-common = [
    "kotlinx-coroutines-core",
    "ktor-client-core",
    "ktor-client-encoding",
    "ktor-client-logging",
    "ktor-client-auth",
    "ktor-serialization-kotlinx-json",
    "ktor-client-content-negotiation",
    "kermit"
]
ktor-android = [
    "ktor-client-okhttp",
    "kotlinx-coroutines-android",
]
ktor-ios = [
    "ktor-client-darwin"
]
ktor-desktop = [
    "ktor-client-cio",
    "kotlinx-coroutines-swing"
]

# Koin
koin-common = [
    "kotlinx-coroutines-core",
    "koin-core",
    "koin-annotations",
]
koin-common-compose = [
    "koin-compose",
    "koin-compose-viewmodel",
    "koin-compose-viewmodel-navigation"
]
koin-common-compiler = [
    "koin-ksp-compiler"
]
koin-common-test = [
    "koin-test"
]

# Room
room-common = [
    "room-runtime",
    "room-sqlite-bundled"
]
room-common-compiler = [
    "room-compiler"
]

# Compose
compose-common = [
    "compose-runtime",
    "compose-foundation",
    "compose-material3",
    "compose-ui",
    "compose-components-resources",
    "compose-ui-tooling-preview"
]
compose-adaptive-bundle = [
    "kotlinx-serialization",
    "compose-adaptive",
    "compose-adaptive-layout",
    "compose-adaptive-navigation",
    "jetbrains-navigation3-ui",
    "jetbrains-lifecycle-viewmodelNavigation3",
]

[plugins]

android-application = { id = "com.android.application", version.ref = "agp" }
multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
android-lint = { id = "com.android.lint", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "cmp" }
compose-hot-reload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "room" }

# Internal Plugins
foundation-project-library = { id = "foundation.kmp.library" }
foundation-library-compose = { id = "foundation.compose" }
foundation-library-koin = { id = "foundation.koin" }
foundation-library-ktor = { id = "foundation.ktor" }
foundation-library-room = { id = "foundation.room" }